/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/public/v1/quote-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a quote or consultation request; confirmation e-mails are in the Accept-Language language */
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/media/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** File content (image or PDF) */
        get: operations["content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company profile */
        get: operations["profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/company/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Partner brands shown on the website */
        get: operations["partners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/catalog/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search published products by words or part number, optionally within a category and brand */
        get: operations["products"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/catalog/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product page */
        get: operations["product"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/catalog/products/slugs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Slug and last change of every published product, for sitemaps */
        get: operations["productSlugs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/catalog/part-numbers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Look up published products by a list of part numbers */
        get: operations["partNumbers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Category tree */
        get: operations["categories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/catalog/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brands in the catalog */
        get: operations["brands"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ContactDto: {
            name?: string;
            email?: string;
            phone?: string;
            company?: string | null;
            taxCode?: string | null;
            address?: string | null;
        };
        LineRequest: {
            productSlug?: string | null;
            partNumber?: string | null;
            description?: string | null;
            /** Format: int32 */
            quantity?: number;
            unit?: string | null;
        };
        SubmitQuoteRequestDto: {
            contact?: components["schemas"]["ContactDto"];
            /** @enum {string} */
            type?: "QUOTE" | "CONSULTATION";
            message?: string | null;
            lines?: components["schemas"]["LineRequest"][];
            website?: string | null;
        };
        SubmittedResponse: {
            reference?: string;
            /** @enum {string} */
            status?: "NEW" | "IN_REVIEW" | "QUOTED" | "WON" | "LOST" | "CLOSED" | "CANCELLED";
            /** Format: date-time */
            submittedAt?: string;
        };
        PublicCompanyProfileResponse: {
            legalName?: string;
            shortName?: string;
            tagline?: string | null;
            /** Format: int32 */
            foundedYear?: number | null;
            headquarters?: string | null;
            taxCode?: string | null;
            email?: string;
            hotlines?: components["schemas"]["PublicHotline"][];
            domains?: string[];
            aboutSections?: components["schemas"]["PublicSection"][];
            highlights?: components["schemas"]["PublicSection"][];
            milestones?: components["schemas"]["PublicMilestone"][];
            technicalDocuments?: components["schemas"]["PublicDocumentLink"][];
            logoUrl?: string | null;
        };
        PublicDocumentLink: {
            title?: string;
            url?: string;
        };
        PublicHotline: {
            /** @enum {string} */
            type?: "SALES" | "SUPPORT";
            phone?: string;
            label?: string | null;
        };
        PublicMilestone: {
            /** Format: int32 */
            year?: number;
            title?: string;
            description?: string | null;
        };
        PublicSection: {
            title?: string;
            body?: string;
        };
        PublicPartnerBrandResponse: {
            slug?: string;
            name?: string;
            description?: string | null;
            websiteUrl?: string | null;
            logoUrl?: string | null;
        };
        FacetResponse: {
            slug?: string;
            name?: string;
            /** Format: int64 */
            count?: number;
        };
        FacetsResponse: {
            categories?: components["schemas"]["FacetResponse"][];
            brands?: components["schemas"]["FacetResponse"][];
        };
        PriceResponse: {
            /** @enum {string} */
            type?: "CONTACT_FOR_PRICE" | "FIXED";
            /** Format: int64 */
            amount?: number | null;
            currency?: string | null;
        };
        ProductSearchResponse: {
            items?: components["schemas"]["PublicProductSummaryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalItems?: number;
            /** Format: int32 */
            totalPages?: number;
            facets?: components["schemas"]["FacetsResponse"] | null;
        };
        PublicProductSummaryResponse: {
            slug?: string;
            name?: string;
            summary?: string | null;
            brand?: components["schemas"]["RefResponse"] | null;
            category?: components["schemas"]["RefResponse"] | null;
            imageUrl?: string | null;
            partNumbers?: string[];
            /** Format: int32 */
            variantCount?: number;
            price?: components["schemas"]["PriceResponse"];
            /** Format: date-time */
            updatedAt?: string;
        };
        RefResponse: {
            slug?: string;
            name?: string;
        };
        CommercialResponse: {
            origin?: string | null;
            warranty?: string | null;
            condition?: string | null;
            documents?: string | null;
            delivery?: string | null;
        };
        MediaResponse: {
            url?: string;
            filename?: string;
        };
        PublicProductDetailResponse: {
            slug?: string;
            name?: string;
            summary?: string | null;
            description?: string | null;
            highlights?: string[];
            brand?: components["schemas"]["RefResponse"] | null;
            categories?: components["schemas"]["RefResponse"][];
            specifications?: components["schemas"]["SpecResponse"][];
            variants?: components["schemas"]["VariantResponse"][];
            price?: components["schemas"]["PriceResponse"];
            commercial?: components["schemas"]["CommercialResponse"];
            images?: components["schemas"]["MediaResponse"][];
            documents?: components["schemas"]["MediaResponse"][];
            /** Format: date-time */
            updatedAt?: string;
        };
        SpecResponse: {
            name?: string;
            value?: string;
        };
        VariantResponse: {
            partNumber?: string;
            label?: string | null;
            orderCode?: string | null;
            specifications?: components["schemas"]["SpecResponse"][];
            price?: components["schemas"]["PriceResponse"] | null;
        };
        ProductSlugResponse: {
            slug?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PartNumberMatchResponse: {
            query?: string;
            partNumber?: string;
            productSlug?: string;
            productName?: string;
        };
        CategoryNodeResponse: {
            slug?: string;
            name?: string;
            description?: string | null;
            children?: components["schemas"]["CategoryNodeResponse"][];
        };
        PublicBrandResponse: {
            slug?: string;
            name?: string;
            description?: string | null;
            websiteUrl?: string | null;
            logoUrl?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitQuoteRequestDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmittedResponse"];
                };
            };
        };
    };
    content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicCompanyProfileResponse"];
                };
            };
        };
    };
    partners: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicPartnerBrandResponse"][];
                };
            };
        };
    };
    products: {
        parameters: {
            query?: {
                q?: string;
                category?: string;
                brand?: string;
                page?: number;
                size?: number;
                facets?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductSearchResponse"];
                };
            };
        };
    };
    product: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicProductDetailResponse"];
                };
            };
        };
    };
    productSlugs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductSlugResponse"][];
                };
            };
        };
    };
    partNumbers: {
        parameters: {
            query: {
                pn: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PartNumberMatchResponse"][];
                };
            };
        };
    };
    categories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryNodeResponse"][];
                };
            };
        };
    };
    brands: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicBrandResponse"][];
                };
            };
        };
    };
}
